name: Test and Deploy
on: push
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v3
        - name: Setup NodeJS correct version
          uses: actions/setup-node@v3
            with:
              node-version: 16
        - name: Lint
          run: npm run lint
        - name: Test
          run: npm run test
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v3
        - name: Setup NodeJS correct version
          uses: actions/setup-node@v3
            with:
              node-version: 16
        - name: Build
          run: npm run build
        - name: Deploy
          run: echo "Deploying..."